version: '3'

networks:
  controle-membros:
    driver: bridge

services:
  controle-membros-db:
    image: postgres:14
    container_name: controle-membros-db
    restart: always
    tty: true
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=controle_membros
    volumes:
      - /var/docker/postgresql:/var/lib/postgresql/data
    networks:
      - controle-membros
    ports:
      - "5432:5432"

  controle-membros-redis:
    image: docker.io/bitnami/redis:6.2
    container_name: controle-membros-redis
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_AOF_ENABLED=no
      - REDIS_PASSWORD=root
    volumes:
      - '/var/docker/redis:/bitnami/redis/data'
    networks:
      - controle-membros
    ports:
      - '6379:6379'

  controle-membros-node:
    build: .
    container_name: controle-membros-node
    entrypoint: dockerize -wait tcp://controle-membros-db:5432 -timeout 20s yarn start
    tty: true
    restart: always
    networks:
      - controle-membros
    depends_on:
      - controle-membros-db
      - controle-membros-redis

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: controle-membros-nginx
    networks:
      - controle-membros
    ports:
      - '80:80'
    depends_on:
      - controle-membros-node

