FROM nginx:1.15.0-alpine

# Remove config
RUN rm /etc/nginx/conf.d/default.conf

# Copy config to container
COPY nginx.conf /etc/nginx/conf.d

# Test config
RUN nginx -t

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]
