version: '3'

networks:
  controle-membros:
    driver: bridge

services:
  controle-membros-db:
    image: postgres:14
    container_name: controle-membros-db
    restart: always
    tty: true
    volumes:
      - /var/docker/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=controle_membros
    networks:
      - controle-membros
    ports:
      - "5432:5432"

  controle-membros-node:
    build: .
    container_name: controle-membros-node
    entrypoint: dockerize -wait tcp://controle-membros-db:5432 -timeout 20s yarn start
    tty: true
    restart: always
    networks:
      - controle-membros
    depends_on:
      - controle-membros-db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: controle-membros-nginx
    networks:
      - controle-membros
    ports:
      - '80:80'
    depends_on:
      - controle-membros-node

